### ISSUE TITLE
Deprecation warnings Python 3.8

### ISSUE THREAD

**Issue by rexop** [elektito/ih2torrent#16]
I get the following warnings since Python 3.8:

> /home/ih2torrent.py:378: DeprecationWarning: "@coroutine" decorator is depcated since Python 3.8, use "async def" instead
>   def ping(loop, host, port):
> /home/ih2torrent.py:450: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
>   def dns_resolve(loop, name):
> /home/ih2torrent.py:460: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
>   def get_metadata(loop, host, port, infohash):
> /home/ih2torrent.py:565: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
>   def get_metadata_with_retries(loop, host, port, infohash):
> /home/ih2torrent.py:604: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
>   def ih2torrent(loop, infohash, filename, bootstrap):
> /home/ih2torrent.py:773: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
>   pending = asyncio.Task.all_tasks()

I also get this error a few times:

> Traceback (most recent call last):
>   File "/home/ih2torrent.py", line 784, in <module>
>     main()
>   File "/home/ih2torrent.py", line 777, in main
>     loop.run_until_complete(asyncio.gather(*pending))
>   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
> asyncio.exceptions.CancelledError`

The code still works, but it's spitting out above's warnings/errors.

**Comment by elektito** [comment]
Fixed. Thanks for reporting the issue.
